markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""
encoding: UTF-8

gauges_id: 
google_analytics_id: 
cnzz_id: 1253874436

repository: https://github.com/AcePeak

collections:
  docs:
    output: true
